name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Install the packages
        run: |
          sudo apt update
      - uses: actions/checkout@v1
      - name: Init
        run: make init
      - name: Configure
        run: |
          make install.pkgs
          make install.jdk
          make conf.jdk
          make install.ant
          make conf.ant
      - name: Build
        run: |
          make build
          make install
      - name: Exist
        run: make exist

