name: Build

on:
  push:
    branches: [ master ]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt update -y
          sudo apt install -y curl openssl sed wget sudo tree unzip make build-essential gcc tomcat9 tomcat9-common tomcat9-admin tomcat9-user libtomcat9-java jsvc
          make init
          make install.jdk
          make conf.jdk
          make install.ant
          make conf.ant
          make build
          make install
          make exist
          make conf.archappl.show
    
  Debian10:
    runs-on: ubuntu-latest
    container: debian:stable
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt update -y
          sudo apt install -y curl openssl sed wget sudo tree unzip make build-essential gcc tomcat9 tomcat9-common tomcat9-admin tomcat9-user libtomcat9-java jsvc
          make init
          make install.jdk
          make conf.jdk
          make install.ant
          make conf.ant
          make build
          make install
          make exist
          make conf.archappl.show
      
  CentOS7:
    runs-on: ubuntu-latest
    container: centos:7
    steps:
      - uses: actions/checkout@v2
      - run: |
          yum update -y
          yum install -y git make sudo
          make init
          make install.pkgs
          make install.jdk
          make conf.jdk
          make install.ant
          make conf.ant
          make build
          make install
          make exist
          make conf.archappl.show
      
  Rocky8:
    runs-on: ubuntu-latest
    container: rockylinux/rockylinux
    steps:
      - uses: actions/checkout@v2
      - run: |
          dnf update -y
          dnf install -y git make sudo
          make init
          make install.pkgs
          make install.jdk
          make conf.jdk
          make install.ant
          make conf.ant
          make build
          make install
          make exist
          make conf.archappl.show
      
